name: Nextflow Workflow Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run CI Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin
        nextflow -version

    - name: Run Nextflow pipeline with test profile
      run: |
        nextflow run main.nf -profile test
